### ISSUE TITLE
Move style guide to repository

### ISSUE THREAD

**Issue by jklmnn** [Componolit/ada-style#1]
Currently the style guide is in the Wiki which makes it hard to propose and review changes. I'd like to move it to the repository. Should it go directly into the README or do we want to use multiple different files?

**Comment by jklmnn** [comment]
We could also store a default switches.gpr with our preferred style switches in this repository.

**Comment by senier** [comment]
Let's use `README.md` until we see need for multiple files.

**Comment by jklmnn** [comment]
Fixed with #4.
