### ISSUE TITLE
Indentation of multi-line conditions

### ISSUE THREAD

**Issue by treiher** [Componolit/ada-style#12]
The current style looks quite strange:

```Ada
if
   (((<condition>
     and then <condition>)
    or else <condition>)
   and then <condition>)
then
   <statements>
end if;
```

As far as I remember the only reason for choosing this style was that GPS supported automatic formatting for it. This seems to have changed. Here is the same code formatted by GNATstudio 20.0:

```Ada
   if
     (((<Condition>
        and then <Condition>)
       or else <Condition>)
      and then <Condition>)
   then
      <Statements>
   end if;
```

This indentation style is still not great for readability in my opinion, but better as the current one. So I would suggest to change it.

**Comment by senier** [comment]
> This indentation style is still not great for readability in my opinion, but better as the current one. So I would suggest to change it.

I agree.

**Comment by jklmnn** [comment]
I'm also in favor of the second variant.
