### ISSUE TITLE
If with multi-line conditions

### ISSUE THREAD

**Issue by treiher** [Componolit/ada-style#13]
The style of if statements and if expressions is not consistent. Also `elsif` and `else` branches are not (always) considered.

### Current Style

Statement:

```Ada
if
   (((<condition>
     and then <condition>)
    or else <condition>)
   and then <condition>)
then
   <statements>
end if;
```

Expression:

```Ada
(if <condition>
 then <expression>
 else <expression>)
```

### Suggestion

Statement:

```Ada
if
   (((<condition>
     and then <condition>)
    or else <condition>)
   and then <condition>)
then
   <statements>
elsif
   (((<condition>
     and then <condition>)
    or else <condition>)
   and then <condition>)
then
   <statements>
else
   <statements>
end if;
```

Expression:

```Ada
(if
   (((<condition>
     and then <condition>)
    or else <condition>)
   and then <condition>)
 then
   <expression>
 elsif
   (((<condition>
     and then <condition>)
    or else <condition>)
   and then <condition>)
 then
   <expression>
 else
   <expression>)
```

**Comment by senier** [comment]
This make me wonder about line breaks. If the `if` has a complex condition that requires line breaks, do we put the `elsif` condition on a different line (even if it's short). Or are linebreaks decided per `if`/`elsif`?

I'm leaning towards having it consistent across all conditions in one `if` block. Either all conditions are on a separate line, or none is.

**Comment by treiher** [comment]
I lean towards that, too.
