### ISSUE TITLE
Consistency

### ISSUE THREAD

**Issue by senier** [Componolit/ada-style#17]
# Parameters of same type

We have this example in the style guide:

```Ada
function "+" (Left, Right : Integer) return Integer with
   Pre  => True,
   Post => True;

function "+" (Left : Integer; Right : Boolean) return Integer with
   Pre  => True,
   Post => True;
```

IMHO we should not mix the example for operators with the two parameter styles. Do we want to add a rule for comma-separated parameters? If so, I'd suggest to only use them if all parameters are of the same type.

# Type place holders

```Ada
function Bar return <type_name> is
   <declarations>
begin
   <statements>
end Bar;
```

This is the only place where `<type_name>` is used, we have specific example types elsewhere. IMHO we should drop it and replace it by e.g. `Boolean`.

**Comment by treiher** [comment]
> If so, I'd suggest to only use them if all parameters are of the same type.

Why is that? What is the disadvantage of the following:

```Ada
   function Valid_Context (Buffer_First, Buffer_Last : Types.Index;
                           First, Last               : Types.Bit_Index;
                           Buffer                    : Types.Bytes_Ptr;
                           Cursors                   : Field_Cursors) return Boolean is
```

**Comment by senier** [comment]
What I dislike about the comma separated parameters is that there is no clear rule on when to use them. The above example looks more concise as related pairs of parameters are grouped. But, would you still use it for 3, 4 or 5 parameters of the same type? And if the parameter list grows too long for the line, what would you do? break at commas? Use separate types?

I think this is too much thought for such a minor benefit. It's only relevant for subprogram signatures, not when using the subprograms anyway. TBH, I wouldn't mind disallowing comma-separated altogether.

Or am I missing some decisive advantage here?
