### ISSUE TITLE
Long case alternative

### ISSUE THREAD

**Issue by senier** [Componolit/ada-style#18]
We need a rule to handle long case alternatives (i.e. when using `|`):

```Ada
     ((case Val.Fld is
         when F_Initial | F_Length | F_Modular_Vector | F_Range_Vector | F_Enumeration_Vector | F_AV_Enumeration_Vector =>
            True,
         when F_Final =>
            False));
```

Suggestion:

```Ada
     ((case Val.Fld is
         when F_Initial
            | F_Length
            | F_Modular_Vector
            | F_Range_Vector
            | F_Enumeration_Vector
            | F_AV_Enumeration_Vector =>
            True,
         when F_Final =>
            False));
```

For consistency, this should happen for all alternatives if at least one alternative does not fit onto a single line.

**Comment by treiher** [comment]
I like that idea. But one issue is that the case alternative is not visibly distinguishable from the dependent expression as both have the same indentation. Another problem is that it is not supported by GNATstudio:

```Ada
     ((case Val.Fld is
         when F_Initial
           | F_Length
             | F_Modular_Vector
               | F_Range_Vector
                 | F_Enumeration_Vector
                   | F_AV_Enumeration_Vector =>
                      True,
         when F_Final =>
            False));
```

**Comment by jklmnn** [comment]
I second the bad visibility of the case alternative. However I wouldn't take GNATstudio support into account. There are many other things that it doesn't support correctly (see indentation of `and then` in contracts, indentation of the first aspect in a package and so on).

**Comment by senier** [comment]
What I don't like about the staircase option is that the case alternatives are visually offset even though they are totally equal. Also, if you have different numbers of alternatives, then expressions start at different columns. I agree that the expressions should be distinguishable, e.g.

```Ada
     ((case Val.Fld is
         when F_Initial
            | F_Length
            | F_Modular_Vector
            | F_Range_Vector
            | F_Enumeration_Vector
            | F_AV_Enumeration_Vector =>
               True,
         when F_Final =>
               False));
```

**Comment by treiher** [comment]
I don't like the staircase option either, but it is what GNATstudio produces. As GNATstudio is the only suitable option for using SPARK in the moment (especially if you want to prove complex code regularly), I think we cannot ignore it. Ignoring would mean that I have to manually work against the tool whenever GNATstudio prefers another style.

>  There are many other things that it doesn't support correctly (see indentation of `and then`

Actually, we selected the indentation style of multi-line conditions just because of its GNATstudio support. The reason was that we do not want to add additional manual effort to change the indentation.

I think ignoring GNATstudio is only an option if we have a tool which creates the correct formatting automatically.

**Comment by senier** [comment]
It think we should decide what the purpose of this style guide is:

1. The least-annoying style possible with GNATstudio
2. The most favorable style we could use as a basis for a formatting tool ("Black for Ada")

So far, I usually had 2. in mind. However, I fully agree that it's worth nothing to have a super-nice coding style which requires constant fighting against the tools.

I don't think we will have the time to build a formatting tool anytime soon. IMHO there are the following short-term options:

- Define both, the most favorable style and the least-annoying style possible with GNATstudio
- Look into making GNATstudio do what we want (possibly opening a ticket)

**Comment by jklmnn** [comment]
I think we should allow/define both variants in this case. I understand the issues with working against GNATstudio but on the other hand I don't want to give up a (IMO) better style because of insufficient tools.

**Comment by senier** [comment]
Switching `Preferences > Editor > Ada > Auto Indentation` to "Simple" seems to get in the way less. But that may result in nasty behavior in other places. IMHO the only proper solution is a plugin that changes GNATstudios auto-intent behavior to our needs.

**Comment by senier** [comment]
Cf. T506-018
