### ISSUE TITLE
Multiline contracts

### ISSUE THREAD

**Issue by jklmnn** [Componolit/ada-style#19]
I noticed that we only defined contracts with a single line in the subprogram examples. I've seen 3 versions:

My preference:
```Ada
procedure P with
   Pre  => <condition>
           and then <condition>,
   Post => <condition>
           and then <condition>;
```

Currently used in RecordFlux:
```Ada
procedure P with
   Pre =>
      <condition>
      and then <condition>,
   Post =>
      <condition>
      and then <condition>;
```

GNATstudio:
```Ada
procedure P with
   Pre => <condition>
   and then <condition>,
   Post => <condition>
   and then <condition>;
```

**Comment by senier** [comment]
I'm undecided between option 1 & 2, but lean towards the RecordFlux variant, as the visual separation between pre- and postcondition is a bit better. The GNATstudio variant is clearly unfavorable (and a bug, IMHO) which brings us back to the discussion in https://github.com/Componolit/ada-style/issues/18#issuecomment-624121306.
