### ISSUE TITLE
Indentation of aspects

### ISSUE THREAD

**Issue by treiher** [Componolit/ada-style#21]
The indentation of aspects is inconsistent:

```Ada
function Bar (A : Natural;
              B : Natural) return Natural with
  Pre  => True,
  Post => True;
```

```Ada
function "+" (Left, Right : Integer) return Integer with
   Pre  => True,
   Post => True;
```

I would prefer to use two spaces. This variant is used by GNAT Studio by default and is consistent to the [Ada Style Guide](https://en.wikibooks.org/wiki/Ada_Style_Guide/Source_Code_Presentation#Indentation):

> Use two spaces as the basic unit of indentation for continuation lines.

**Comment by jklmnn** [comment]
Is this something we could change in GNAT Studio? While I agree with staying consistent with the style guide I'd prefer using the same indentation level everywhere. I cannot see any advantage in switching between 2 and 3 spaces except of the style guide saying so.
Also the style guide suggests 2 spaces for continuation lines but from looking at the examples I cannot safely tell what counts as continuation line and what doesn't.

**Comment by senier** [comment]
I don't have a strong opinion here and my code was inconsistent in that respect in the past. I agree that we should not work against GNAT studio (and it's probably safe to assume that this behavior cannot be changed easily).

> I cannot see any advantage in switching between 2 and 3 spaces except of the style guide saying so.

You have a point here. Without other constraints I'd just define 3 spaces as the one indentation. However, given the fact that you need GNAT studio for proving, we should see which style causes least resistance.

**Comment by jklmnn** [comment]
> I agree that we should not work against GNAT studio (and it's probably safe to assume that this behavior cannot be changed easily).

This can be changed in Preferences->Editor->Ada under Continuation Lines. I have changed this to 3 and it's working for me.

**Comment by senier** [comment]
> This can be changed in Preferences->Editor->Ada under Continuation Lines. I have changed this to 3 and it's working for me.

Fair enough. @treiher, what do you think? I'd opt for a consistent three space layout then as (1) two spaces give little additional visual separation or any other benefit, (2) it's one rule less that needs to be followed (3) GNAT Studio can be configured to support it.

**Comment by treiher** [comment]
I get your point. I'm also fine with using three spaces.
