### ISSUE TITLE
Notation of records

### ISSUE THREAD

**Issue by jklmnn** [Componolit/ada-style#22]
I propose a new record type notation:
```Ada
   type Foo_Record is record
      Bar : Natural;
   end record with
      Convention => C;
```
which I find much better readable than the current one in the style guide. Record fields and aspects are still visually separated without unnecessarily increasing the size of the record. For comparison, the old notation:
```Ada
   type Foo_Record is
      record
         Bar : Natural;
      end record
     with
       Convention => C;
```

**Comment by treiher** [comment]
I'm fine with it.

**Comment by senier** [comment]
Me too, this looks cleaner.
