### ISSUE TITLE
Consistency of subprogram definitions

### ISSUE THREAD

**Issue by jklmnn** [Componolit/ada-style#26]
Make subprogram layouts consistent with enumerations (see https://github.com/Componolit/ada-style/issues/24#issuecomment-767397700).

This is the current subprogram style adapted to the new enum style.

#### Procedure

```Ada
procedure Foo
   (A : Natural;
    B : Natural)
with
   Pre  => True,
   Post => True;
```

#### Function

```Ada
function Bar
   (A : Natural;
    B : Natural) return Natural
with
   Pre  => True,
   Post => True;
```

#### Operator

```Ada
function "+" (Left, Right : Integer) return Integer
with
   Pre  => True,
   Post => True;
```

```Ada
function "+" (Left : Integer; Right : Boolean) return Integer
with
   Pre  => True,
   Post => True;
```

### Body

Subprogram bodies should not contain blank lines at all.

#### Procedure

```Ada
procedure Foo is
   <declarations>
begin
   <statements>
end Foo;
```

```Ada
procedure Foo
   (A : Natural;
    B : Natural)
with
   Pre  => True,
   Post => True
is
   <declarations>
begin
   <statements>
end Bar;

```

#### Function

```Ada
function Bar return <type_name> is
   <declarations>
begin
   <statements>
end Bar;
```

```Ada
function Bar
   (A : Natural;
    B : Natural) return Natural
with
   Pre  => True,
   Post => True
is
   <declarations>
begin
   <statements>
end Bar;
```

```Ada
function Bar (N : Natural) return Natural is
  (N + 1)
  with
    Pre => N <= 42;
```

What are your opinions on how to handle the `return` in functions?

**Comment by treiher** [comment]
I think having the `return` on the same line as the last parameter can be problematic for long identifiers:

```Ada
function Bar
   (Some_Name : Some_Package.Some_Type;
    Other_Name : Some_Other_Package.Some_Type) return Some_Other_Package.Some_Other_Type;
with
   Pre  => True,
   Post => True;
```

In some cases, the distinction between parameter types and return type is not visually clear (although syntax highlighting alleviates the problem):

```Ada
function Bar
   (A : Some_Other_Package.Some_Other_Type;
    B : Some_Type) return Other_Type;
with
   Pre  => True,
   Post => True;
```

A `return` on a separate line looks strange to me, but is probably better:

```Ada
function Bar
   (A : Some_Package.Some_Type;
    B : Some_Other_Package.Some_Type)
return Some_Other_Package.Some_Other_Type
with
   Pre  => True,
   Post => True;
```

**Comment by jklmnn** [comment]
I get the point with long identifiers. I already had to add a new line for return on some occasions. What do you think about aligning the return with the parentheses or indenting it?
```Ada
function Bar
   (A : Some_Package.Some_Type;
    B : Some_Other_Package.Some_Type)
   return Some_Other_Package.Some_Other_Type
with
   Pre  => True,
   Post => True;
```

```Ada
function Bar (A : Some_Package.Some_Type;
              B : Some_Other_Package.Some_Type)
   return Some_Other_Package.Some_Other_Type
with
   Pre  => True,
   Post => True;
```
It's not perfect but I think it collides less with the `with` on the next line.

**Comment by senier** [comment]
I guess I'll have to bring up a third option, just so we don't have to few. How about putting the return type onto a separate line and indent it? This would be consistent with `with`:

```Ada
function Bar
   (A : Some_Package.Some_Type;
    B : Some_Other_Package.Some_Type)
return
   Some_Other_Package.Some_Other_Type
with
   Pre  => True,
   Post => True;
```
A bit strange, but at least there is good visual separation between function signature, return value and with-clauses...

**Comment by treiher** [comment]
> How about putting the return type onto a separate line and indent it?

Of the three options, I like it the most because of the visual separation.

**Comment by jklmnn** [comment]
I'm also fine with the third option. It follows the concept of having different blocks separated by keywords.
